name = "MFF"
uuid = "99a43ef4-9f3f-47d4-9871-ef3d7e68cea8"
authors = ["Shayan Davoodi"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
